package com.noice.productbff.enums;

public enum Department {
    BOOKS,
    ELECTRONICS,
    ELECTRONICS_ACCESSORIES,
    FASHION,
    HOME_KITCHEN,
    BEAUTY,
    TOYS_GAMES,
    SPORTS_OUTDOORS,
    AUTOMOTIVE,
    GROCERY_GOURMET,
    HEALTH_PERSONAL_CARE,
    PET_SUPPLIES,
    JEWELRY_WATCHES,
    TOOLS_HOME_IMPROVEMENT,
    OFFICE_SUPPLIES,
    BABY_KIDS,
    MUSIC_MOVIES,
    GARDEN_PATIO,
    ART_CRAFT_SEWING,
    VIDEO_GAMES,
    SOFTWARE
}

